#!/bin/bash

curl -sX POST -H 'Content-type: application/json' --data '{"text":"$(date +%Y-%m-%d\ %H:%M) Update Started"}' $SLACK_HOOK >> /dev/stdout 2>&1

rsync -vaze "ssh -p $PORT" root@$SERVER_ADDRESS:/var/backup/ /var/backup/ >> /dev/stdout 2>&1

curl -sX POST -H 'Content-type: application/json' --data '{"text":"$(date +%Y-%m-%d\ %H:%M) Update Finished"}' $SLACK_HOOK >> /dev/stdout 2>&1
