#!/bin/bash

RUN=`ps -aux | grep -i rsync | wc -l`

if [ "$RUN" -le "1" ]
then
        echo "$(date +%d.%m.%Y\ %H:%M) Backup Started"
        curl -sX POST -H 'Content-type: application/json' --data '{"text":"Backup Started\n'"$(df -h /var/backup/)"'"}' $SLACK_HOOK

        rsyncOutput=$(rsync -vaze "ssh -p $PORT" root@$SERVER_ADDRESS:/var/backup/ /var/backup/  | sed '0,/^$/d')
        echo "$(date +%d.%m.%Y\ %H:%M) $rsyncOutput"

        echo "$(date +%d.%m.%Y\ %H:%M) Backup Finished"
        curl -sX POST -H 'Content-type: application/json' --data '{"text":"Backup Finished\n'"$(df -h /var/backup/)"'\n'"$rsyncOutput"'"}' $SLACK_HOOK
else
        echo "$(date +%d.%m.%Y\ %H:%M) Backup Already Running"
        curl -sX POST -H 'Content-type: application/json' --data '{"text":"Backup Already Running\n'"$(df -h /var/backup/)"'"}' $SLACK_HOOK
fi
