#!/bin/bash

echo "$(date +%Y-%m-%d\ %H:%M) Backup Started" >> /var/log/cron.log 2>&1
curl -sX POST -H 'Content-type: application/json' --data '{"text":"Backup Started"}' $SLACK_HOOK >> /var/log/cron.log 2>&1

rsync -vaze "ssh -p $PORT" root@$SERVER_ADDRESS:/var/backup/ /var/backup/ >> /var/log/cron.log 2>&1

echo "$(date +%Y-%m-%d\ %H:%M) Backup Started" >> /var/log/cron.log 2>&1
curl -sX POST -H 'Content-type: application/json' --data '{"text":"Backup Finished"}' $SLACK_HOOK >> /var/log/cron.log 2>&1
